# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - install
  - test
  - lint
  - build
  - release

install:
  stage: install
  script:
    - yarn install --cache-folder .yarn

unit-test:
  stage: test
  script:
    - yarn test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  needs: ["install"]
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml

lint:
  stage: lint
  needs: ["install"]
  script:
    - yarn lint

build:
  stage: build
  needs: ["install", "test"]
  script:
    - yarn run build

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.